export enum ActionType {
   GET_WEATHER_REQUEST = "GET_WEATHER_REQUEST",
   GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS",
   GET_WEATHER_FAIL = "GET_WEATHER_FAIL",
   WEATHER_TYPE_REQUEST = "WEATHER_TYPE_REQUEST",
   WEATHER_TYPE_SUCCESS = "WEATHER_TYPE_SUCCESS",
   WEATHER_TYPE_FAIL = "WEATHER_TYPE_FAIL",
   GEOLOCATION_REQUEST = "GEOLOCATION_REQUEST",
   GEOLOCATION_SUCCESS = "GEOLOCATION_SUCCESS",
   GEOLOCATION_FAIL = "GEOLOCATION_FAIL",
};